### ISSUE TITLE
Allow filtering of stale/outdated lists

### ISSUE THREAD

**Issue by KonoromiHimaries** [collinbarrett/FilterLists#182] opened 2018-01-17 23:11 UTC
pls remove all unsupported lists from your page
`https://filterlists.com/`

example. 

Adblock Polska
`! Last modified: 07 Nov 2014 22:20 UTC`
```
https://raw.githubusercontent.com/adblockpolska/Adblock_PL_List/master/adblock_polska.txt
```

**Comment by collinbarrett** [comment] 2018-01-17 23:14
Thanks for the suggestion!

The goal of this project is to index all lists including those that are old. As, they may still serve some purpose to somebody.

But, you bring up a great point that we should make it easier to filter those out or even filter them out by default.

**Comment by collinbarrett** [comment] 2018-01-17 23:14
related to #48 and #6

**Comment by KonoromiHimaries** [comment] 2018-01-17 23:14
@collinbarrett you can separate this list

**Comment by Atavic** [comment] 2018-01-18 18:37
:+1: Keep but create a *Top* or *Fresh* section with *Others* on bottom IMHO

**Comment by collinbarrett** [comment] 2018-01-25 03:03
Closing into duplicate of #154

**Closed by collinbarrett** 2018-01-25 03:03 UTC
Labels: duplicate, enhancement
