### ISSUE TITLE
Feature request: Last update date

### ISSUE THREAD

**Issue by 4DEATH** [collinbarrett/FilterLists#3170] opened 2022-07-01 18:14 UTC
A column that shows last update date of filter list could be useful, if possible. Thank you.

**Comment by collinbarrett** [comment] 2022-07-01 18:17
I totally agree. We used to have this a long time ago before the database was as big as it is today, and the architecture of the app has changed a lot. Definitely want to bring this back.

Closing as duplicate of #371

**Closed by collinbarrett** 2022-07-01 18:17 UTC
