### ISSUE TITLE
Language endpoint for the URL

### ISSUE THREAD

**Issue by nimasaj** [collinbarrett/FilterLists#2807] opened 2022-02-16 15:48 UTC
Would it be possible for you to add endpoint, for languages, to the URL? 
It'd be great to have the language endpoint on the URL. Therefore, a link with an endpoint for a specific language, that is filtering the lists based on that specific language on your page, would be available to list maintainers.

**Comment by nimasaj** [comment] 2022-02-16 17:31
Thanks for the question.
I assume having a dynamic URL such as "https://filterlists.com/?lng=en" would bring more flexibility on your side to support more features and add other parameters to the URL in the future, rather than a static page for each language.

In this way, the lists could, also, be sorted & filtered by tags or maintainers name if they have developed more than a list ( e.g. "https://filterlists.com/?mnt={name}"

or a combination of parameters (e.g. "https://filterlists.com/?lng=en&tag=crypto")

**Comment by collinbarrett** [comment] 2022-02-16 17:34
Excellent. Thanks for the suggestion and details. I am going to close this as a duplicate of #263. I definitely agree this would be a useful feature. Just gotta find the time. 😀

**Closed by collinbarrett** 2022-02-16 17:34 UTC
Labels: feedback wanted
