### ISSUE TITLE
View Newest Lists?

### ISSUE THREAD

**Issue by hl2guide** [collinbarrett/FilterLists#1294] opened 2020-01-05 14:59 UTC
Please consider adding a way to view/sort the table at https://filterlists.com/ by the newest (date of first published).

**Comment by collinbarrett** [comment] 2020-01-06 14:03
Thanks. We used to have this feature, but it's been disabled due to #784 . We will certainly re-enable when we can. But, I just haven't had much time to work on this project recently, so not sure when we'll get it done. Thanks!

Duplicate of #794

**Closed by collinbarrett** 2020-01-06 14:03 UTC
Labels: duplicate, enhancement, ui
