### ISSUE TITLE
add info for required filters list

### ISSUE THREAD

**Issue by KonoromiHimaries** [collinbarrett/FilterLists#457] opened 2018-09-09 00:27 UTC
## Bug or Feature Request?

![2018-09-09-window](https://user-images.githubusercontent.com/5884000/45259868-7eb60a00-b3d7-11e8-878c-f474ccfdb446.png)

```
EasyList, Official Polish Filters, Polish Annoyance Filters
```

**Comment by collinbarrett** [comment] 2018-09-09 00:32
closing as duplicate of #241

**Closed by collinbarrett** 2018-09-09 00:32 UTC
