### ISSUE TITLE
exclude metadata from Rule Counts

### ISSUE THREAD

**Issue by KonoromiHimaries** [collinbarrett/FilterLists#456] opened 2018-09-09 00:12 UTC
## Bug or Feature Request?

![2018-09-09-window](https://user-images.githubusercontent.com/5884000/45259786-49a8b800-b3d5-11e8-869f-ab3d546a103b.png)

![2018-09-09-window](https://user-images.githubusercontent.com/5884000/45259806-b7ed7a80-b3d5-11e8-85f3-d9703f0844b0.png)

**Comment by collinbarrett** [comment] 2018-09-09 00:26
closing as duplicate of #202

**Comment by DandelionSprout** [comment] 2019-04-06 10:12
Could it have worked to change line 34 in https://github.com/collinbarrett/FilterLists/edit/master/src/FilterLists.Services/Snapshot/Batch.cs from `var newRules = lines.Except(existingRules.Select(r => r.Raw)).Select(l => new Rule {Raw = l}).ToList();` to `var newRules = lines.Except(existingRules.Select(r => r.Raw).Select(l = Regex.Match(/!/).Select(l = Regex.Match(/^# /)).Select(l => new Rule {Raw = l}).ToList();`?

I feel exhausted after having tried to figure out for 2 hours how C# coding works, with very limited success.

**Closed** 2020-02-17 02:19 UTC
Labels: agent, blocked
