### ISSUE TITLE
add like button / rating function

### ISSUE THREAD

**Issue by KonoromiHimaries** [collinbarrett/FilterLists#644] opened 2018-12-18 23:21 UTC
## Bug or Feature Request?

example
![2018-12-19-window](https://user-images.githubusercontent.com/5884000/50188991-e27b9780-0323-11e9-98a3-355c6a4e66c0.png)

**Comment by collinbarrett** [comment] 2018-12-19 14:58
Nice. Yeah, I agree this could be cool.

Closing as duplicate of #43 which has been folded into #371 .

**Closed by collinbarrett** 2018-12-19 14:58 UTC
Labels: duplicate, enhancement
