### ISSUE TITLE
support modular lists (via include directives)

### ISSUE THREAD

**Issue by mtxadmin** [collinbarrett/FilterLists#769] opened 2019-04-21 21:47 UTC
Thanks for [adding](https://github.com/collinbarrett/FilterLists/pull/764) my list.

But it seems the engine does not support !#include tags (from uBlock Origin syntax). It looks only at root file with include sets and therefore incorrectly determines "Rule Count" numbers and "Updated" date.

**Comment by collinbarrett** [comment] 2019-04-21 22:01
Hmm, the rule count and updated features are rough estimates and are only designed to be for a single list. We haven't really supported a list that is modular by design (that I can remember). Will have to think about this.

**Comment by mtxadmin** [comment] 2019-04-26 22:06
It seems, include directive supported even by Adblock Plus now? 

See @DandelionSprout 's list
https://github.com/DandelionSprout/adfilt/blob/master/a.txt  :

[Adblock Plus 3.2]
! Title: 🏡 Imres filtre
! Version: 22April2019v5-Personal
! Expires: 12 hours
!#include a2.txt
!#include BrowseWebsitesWithoutLoggingIn.txt
!#include Anti-IMDB%20List.txt
.......

**Comment by DandelionSprout** [comment] 2019-04-27 01:47
I get the feeling that you (mtxadming) are misunderstanding. `!#include` remains unsupported by ABP, and the use of `[Adblock Plus 3.2]` instead of `[Adblock Plus 2.0]` is part of a one-man campaign of mine to intentionally break compatibility with low-quality AdBlock and ABP forks.

**Comment by mtxadmin** [comment] 2019-04-27 20:08
"one-man campaign" - sounds good :-)

I use uBlock last years so don't know about AdBlock Plus innovations. Thought I missed some.

**Comment by mtxadmin** [comment] 2019-04-27 20:09
(uBlock = uBlock Origin, of course)

**Comment by collinbarrett** [comment] 2020-09-13 14:11
the rule count feature has been offline for sometime. I certainly hope to rebuild in the future, but I don't think this particular issue has a specific reason to remain open. closing for now.

**Closed by collinbarrett** 2020-09-13 14:11 UTC
Labels: directory-data

**Comment by mtxadmin** [comment] 2020-09-14 14:39
It's a pity to hear that.
