### ISSUE TITLE
Docker image fails to start

### ISSUE THREAD

**Issue by bountyx** [collinbarrett/FilterLists#2176] opened 2021-01-06 14:32 UTC
Awesome project :)

Just wondering how to get this running, I tried doing docker-compose up in the docker-compose folder but got the following error:

```
ERROR: Service 'directory-api' failed to build : The command '/bin/sh -c dotnet publish --no-restore -o /app/publish -r linux-musl-x64' returned a non-zero code: 1
````

**Comment by collinbarrett** [comment] 2021-01-06 14:48
Hey! Thanks. I think you are the first other than myself to actually try running locally.

I need to get this documented ( #1998 ).

Will try to get some quick steps hammered out in the next couple of days. Unfortunately, I think we need to pass additional flags/options other than just `docker-compose up` to spin up the right volumes/networks etc. Let me refresh my memory and get back to you.

**Comment by collinbarrett** [comment] 2021-01-23 17:57
Closing as duplicate of #1998 . Hoping to get this documented very soon, but, time is hard to find. 😄

**Closed by collinbarrett** 2021-01-23 17:57 UTC
Labels: duplicate, ops, question

**Comment by collinbarrett** [comment] 2021-01-31 22:10
@bountyx Sorry this took so long. I added _basic_ instructions [here](https://github.com/collinbarrett/FilterLists#building-and-running-locally) that should get everything up and running locally. Let me know if you get a chance to try and if it works for you.
