### ISSUE TITLE
add support for direct link to the specyfic list

### ISSUE THREAD

**Issue by KonoromiHimaries** [collinbarrett/FilterLists#458] opened 2018-09-09 00:36 UTC
## Bug or Feature Request?

![2018-09-09-window](https://user-images.githubusercontent.com/5884000/45259937-ee78c480-b3d8-11e8-9c98-862fe6234d91.png)

#### example link
```
https://filterlists.com/#polish-internal-filters
```

**Comment by collinbarrett** [comment] 2018-09-09 00:37
closing as duplicate of #263

**Closed by collinbarrett** 2018-09-09 00:37 UTC
