### ISSUE TITLE
add MajkiIT hosts

### ISSUE THREAD

**Issue by KonoromiHimaries** [collinbarrett/FilterLists#309] opened 2018-06-30 21:01 UTC
https://github.com/MajkiIT/polish-ads-filter/tree/master/polish-pihole-filters

**Comment by collinbarrett** [comment] 2018-06-30 21:05
closing ad duplicate of [list 347](https://github.com/collinbarrett/FilterLists/blob/master/data/FilterList.json)

**Closed by collinbarrett** 2018-06-30 21:05 UTC
Labels: duplicate, new list
