### ISSUE TITLE
add ublock "AdGuard Annoyances filter"

### ISSUE THREAD

**Issue by KonoromiHimaries** [collinbarrett/FilterLists#301] opened 2018-06-09 16:30 UTC
## Bug or Feature Request?

No rules, just let us know what's up in your issue providing all the relevant details.

## Adding or Updating Lists?

Please provide information for all of the fields described here:
https://github.com/collinbarrett/FilterLists/wiki/Data-Model_sidebar

https://filters.adtidy.org/extension/ublock/filters/4.txt

**Comment by collinbarrett** [comment] 2018-06-09 16:40
Thanks. Both Annoyances (from your title) and Social Media (from your link) are added already. Your link specifies ublock version, though, which is not separately added yet. Closing as a duplicate of #103

**Closed by collinbarrett** 2018-06-09 16:40 UTC
Labels: duplicate, new list
