### ISSUE TITLE
Support auto-updating of "description" value from lists' "Description:" tags

### ISSUE THREAD

**Issue by DandelionSprout** [collinbarrett/FilterLists#695] opened 2019-02-15 16:22 UTC
Based in part on #694, and in part on my experiences with AdGuard's desktop version, I propose that the list descriptions in FilterList.json, could be updated from a list's `! Description:` value.

`! Description:` is an AdGuard-only tag, that contains a list description that is to be shown when hovering over a "(?)" button in the paid AdGuard desktop version's list menu, as can be seen in this screencap: 
![image](https://user-images.githubusercontent.com/22780683/52869374-ce96bb00-3145-11e9-9156-a7be8562877a.png)

Because of the few appliances of the tag, it is unfortunately currently **very** rarely used, with AdGuard and me being the only ones to use it on a regular basis.

Additionally, @yourduskquibbles' lists seem to use `! Purpose:` instead, except in the event that he'd be willing to change to `! Description:`.

**Comment by yourduskquibbles** [comment] 2019-02-15 16:35
> Additionally, @yourduskquibbles' lists seem to use `! Purpose:` instead, except in the event that he'd be willing to change to `! Description:`.

I'm fine changing it to whatever works easiest / becomes standardized.

**Comment by collinbarrett** [comment] 2019-02-15 16:52
Agreed. Closing as duplicate of #202 .

**Closed by collinbarrett** 2019-02-15 16:52 UTC
