### ISSUE TITLE
Filter magnifying glass hangs browser on mobile

### ISSUE THREAD

**Issue by gallegonovato** [collinbarrett/FilterLists#2910] opened 2022-04-16 13:41 UTC
Good afternoon:

First of all thank you for a great web site like https://filterlists.com/.

I wanted to tell you about an incident that happens with it to a friend.

It turns out that if you try to use the magnifying glass in Chrome 100 for Android. It stands still, and does not work. And then it stays like this https://ibb.co/wwQd9f7

I tried in other browsers he uses and in fennec or mull without problems.

I do not know if it is a failure of the browser that my friend uses or not.

Thanks for your help and time.

**Comment by collinbarrett** [comment] 2022-04-16 17:03
Hmm. Thanks for reporting the issue...

Yeah, we use react and antd for our front-end website. I'm not sure what this issue could be.

You said it works ok until you try to use the magnifying glass?

**Comment by gallegonovato** [comment] 2022-04-16 17:28
Good afternoon @collinbarrett 

First of all thank you for your help and time.

I just looked on my friend's mobile with Chrome. And I don't know if it is on all. But in the one of the if you press on name or on the magnifying glass. The web stops, or blocks. Or does not work. 

On the other hand, it allows you to go up or down pages. Or enter by clicking on the blue button with the i. And then the description and so on goes.

It seems that only the magnifying glass and the name fails. I even noticed that sometimes if you click on the magnifying glass. It is as if it selects or catches also name.

A hug

**Comment by collinbarrett** [comment] 2022-04-16 17:35
Ok, thanks. Hmm. Sounds like possibly a bug / missing feature in the "antd" UI library we are using. I'm not sure if it's something I will have the time to fix in the near term. But, hopefully they will fix it. Will keep this Issue open for awhile to keep in mind.

Thanks for reporting.

**Comment by gallegonovato** [comment] 2022-04-16 18:56
Good afternoon:

Thank you very much for your help and time.

My friend just sent me a screenshot. What happens if you enter the web. And you mark in Chrome " view as computer "

It seems to be stuck in the same way in the magnifying glass. The screenshot is:

https://ibb.co/4R4GhB6
https://ibb.co/fXsNX4J
https://ibb.co/2WzyYHj
https://ibb.co/tDcKVDQ

It freezes and after a while black screen.

A hug and thanks for your time

**Comment by collinbarrett** [comment] 2022-04-17 19:25
I can reproduce as well. Hmm.

Another similar bug report came in via email:

> Hello, good afternoon. The site that you own, as I understand it, and i.e. filterlists.com hangs very much when entering
When you go to the site and click on the magnifying glass icon, the site just hangs. Up to the point that a notification comes out, saying that the site does not respond.

**Comment by gallegonovato** [comment] 2022-04-19 16:00
Good afternoon:

I was testing yesterday. And I think it even happens in the pc version of Chrome. From what I could see on my friend's computer.

The strange thing is that no one commented anything about this bug. It will be in the new versions of Chrome?

About the email you received, I can't tell you anymore. Since my friend told me about it, and I told you about it on github. Since I've been following your work for a long time :) . But if you got the error too and the person who sent you the email, also gives it to you. I am more reassured that my friend has not done one of his on his mobile.

Thanks for your help

A hug

**Comment by KamiOh** [comment] 2022-04-19 17:22
> Good afternoon:
> 
> I was testing yesterday. And I think it even happens in the pc version of Chrome. From what I could see on my friend's computer.
> 
> The strange thing is that no one commented anything about this bug. It will be in the new versions of Chrome?
> 
> About the email you received, I can't tell you anymore. Since my friend told me about it, and I told you about it on github. Since I've been following your work for a long time :) . But if you got the error too and the person who sent you the email, also gives it to you. I am more reassured that my friend has not done one of his on his mobile.
> 
> Thanks for your help
> 
> A hug
i'm using Firefox 99.0.1 x64 || Winbugs 10 LTSC
![imagen](https://user-images.githubusercontent.com/13822730/164060333-4a9f5e42-9f97-42cc-bf1b-2fdb4e7ca24f.png)

**Comment by gallegonovato** [comment] 2022-04-19 17:35
good afternoon @KamiOh 

from what I see in your comment it also happens to you in Firefox 99.0.1 x64 || Winbugs 10 LTSC However, I tried mull and fennec for android (both) and it works without problems. I even tried lineageos without anything from google. and perfect 

thanks for your note A hug

**Comment by KamiOh** [comment] 2022-04-19 19:04
> good afternoon @KamiOh
> 
> from what I see in your comment it also happens to you in Firefox 99.0.1 x64 || Winbugs 10 LTSC However, I tried mull and fennec for android (both) and it works without problems. I even tried lineageos without anything from google. and perfect
> 
> thanks for your note A hug
PC
i try in Firefox 99.0.1 x64 safe mode too, still same problem so lag.
Brave 1.37.116 x64 || Chromium 110.0.4896.127 without extensions
![aaaaa](https://user-images.githubusercontent.com/13822730/164076186-5835d917-34e9-4cf4-a00e-91d50326b164.png)

Android
Android 11DotOS  GSI Rom || Firefox  99.2
when i touch the red box, the browser stops responding.
![photo_2022-04-19_13-55-44](https://user-images.githubusercontent.com/13822730/164076231-5f103668-c283-4da4-bad8-d307e6f6f3cd.png)

**Comment by gallegonovato** [comment] 2022-04-19 19:40
good evening: 

I just checked in landscape mode, as you have in the photo. Both on Mull and Fennec from fdroid. And if the same thing happens when you click on the icon you mark. 

Sometimes it even works again, or rather it reacts if you hit the back button, without leaving the web If you have it in vertical mode, it goes without problem. In landscape mode I didn't know what was wrong, since I have it disabled.

 I only use portrait mode. But I just noticed that both fdroid fennec and Mull do mark desktop site. It also fails in the magnifying glass icon, like the one you indicate (which is a funnel). 

A hug and thanks for the note.

**Comment by RicoHeat** [comment] 2022-04-21 11:14
I am also having the same issues.. I tried multiple browsers on my Android device and nothing changed.. Any attempt to filter results via search, software selection, syntax..etc.. causes the page to freeze.

**Comment by NDDDDDDDDD** [comment] 2022-04-21 14:01
just so you guys know accessing the website through archive.org still works!

**Comment by gallegonovato** [comment] 2022-04-21 16:24
Good afternoon @collinbarrett

Thank you very much for all your work and effort.

Then we enter the web and see if it goes well.

But it is still giving problems in the magnifying glass in chrome. The web hangs and does not allow to work with it. Both in portrait and landscape mode. And neither asking for view as a computer.

It crashes for example in Mull if you use the vertical mode. The magnifying glass works perfectly. But if you put it in horizontal mode, the icon of the magnifying glass and the magnifying glass fails.

Best regards

**Comment by gallegonovato** [comment] 2022-04-21 18:06
Good afternoon:

I was passed a screenshot of the web in Chrome. It looks like when you hit the magnifying glass, as if it selects the name part and the little arrows up and down as well. As if it were a set, if you look at the screenshots appears in different color to where it says info:

https://ibb.co/sqHtMLc
https://ibb.co/GR3DMt6

Then in firefox based browsers, as long as you don't have the landscape mode active. The magnifying glass is fine. It only fails in landscape mode.

There is no need to thank us, we are here for whatever we can do to help. I wish I was more proficient in programming :(

Best regards

**Comment by gallegonovato** [comment] 2022-04-21 23:13
good evening @collinbarrett 

 I tried on the web and it keeps failing me. Does it go to you? 

A hug

**Comment by collinbarrett** [comment] 2022-04-22 01:53
Oh, sorry, the bug is definitely still there. Didn't mean to have this auto-close.

**Comment by gallegonovato** [comment] 2022-04-22 07:49
Good morning @collinbarrett 

You don't have to apologize for the auto close. It would be missing more, even after all the work you are doing. You don't have to apologize at all. 👍 

I apologize for giving you such a hard time.

And thank you very much for all your work and effort. 🥇

**Comment by dummy-account007** [comment] 2022-04-22 13:30
I am not sure if this helps but when replicating the behavior of previous posts above the CPU usage rises around 7-10%. I can provide steps to replicate behaviour if wanted.

**Comment by collinbarrett** [comment] 2022-04-23 18:09
I _think_ it might be fixed now? Can some of you try again?

I've just been fiddling with rolling back dependency updates on the UI. I'm still not sure what caused it, but if it does work at this stage, I'll keep this current version locked until I have time to investigate more.

**Comment by sosawolfo** [comment] 2022-04-23 19:10
Works for me on Chrome 100.0.4896.127 on Windows. No more freezing.

**Comment by gallegonovato** [comment] 2022-04-24 14:38
Good afternoon @collinbarrett

THANKS A MILLION FOR ALL THE WORK. AND FOR SOLVING THE PROBLEM. 👍 ❤️ 

I HAVE TRIED IT IN SEVERAL BROWSERS AND IT IS PERFECT.

A HUG

**Comment by collinbarrett** [comment] 2022-04-24 14:59
Thanks for confirming @sosawolfo and @gallegonovato . I am going to close this for now. I'm still not sure what caused it (other than it was an issue in one of the UI's dependency packages), but I am working on potentially an entire new version of the site to solve a lot of the pain points, so I'll probably keep the current version "frozen" for now.

**Closed by collinbarrett** 2022-04-24 14:59 UTC
Labels: bug, feedback wanted, web, high priority

**Comment by gallegonovato** [comment] 2022-04-24 15:04
Good afternoon @collinbarrett

You don't have to say thank you. We are here to help.

On the contrary the thanks goes to you for the great work you do. And for solving the problem.

We are looking forward to the new version which I'm sure will be wonderful.

Best regards
